###########
# STARTUP #
###########

$cursor = Bibata-Modern-Ice
exec-once = hyprctl setcursor $cursor 21

$scripts_dir = $HOME/.config/hypr/scripts


# --- STARTUP APPS ---
exec-once = $scripts_dir/startup.sh


exec-once = hyprpaper
exec-once = waybar & hypridle & hyprsunset
exec-once = sh -c 'sleep 5 && "/opt/Mullvad VPN/mullvad-vpn"'
#exec-once = nm-applet &

# Pollicykit
exec-once = $scripts_dir/polkit.sh

# clipboard manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# pyprland
exec-once = pypr
