##############
### SOURCE ###
##############


# Expose the SSH socket (stored in RAM disk) to GUI apps
env = SSH_AUTH_SOCK,$XDG_RUNTIME_DIR/ssh-agent.socket

# Start the agent using the RAM disk path
exec-once = ssh-agent -a $XDG_RUNTIME_DIR/ssh-agent.socket
exec-once = tailscale systray
exec-once = solaar



$configs = ~/.config/hypr/confs
# source=~/.config/hypr/hyprpaper.conf
source=$configs/settings.conf
source=$configs/decoration.conf
source=$configs/startup.conf
source=$configs/windowrules.conf
source=$configs/keybinds.conf
source=$configs/env.conf
source=$configs/animations.conf

source=~/.config/hypr/monitors.conf
source=~/.config/hypr/workspaces.conf

env = XCURSOR_SIZE,21
env = HYPRCURSOR_SIZE,21
env = XCURSOR_THEME,Bibata-Modern-Ice
