preload = ~/Pictures/wallpaper/IMG_6580-2.jpg
preload = ~/.config/hypr/Wallpapers/Gruvbox/gruvbox_spac.jpg
preload = ~/.config/hypr/Wallpapers/TokyoNight/lowpoly_street.png

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wallpaper/IMG_6580-2.jpg
    fit_mode = fill
}

wallpaper {
    monitor = DP-8
    path = ~/.config/hypr/Wallpapers/Gruvbox/gruvbox_spac.jpg
    fit_mode = cover
}

splash = false
