foreground   #b4b9bc
background   #121b1c
cursor       #b4b9bc

color0       #121b1c
color8       #7d8183

color1       #e67e80
color9       #e67e80

color2       #a7c080
color10      #a7c080

color3       #8D706F
color11      #8D706F
color4       #728970
color12      #728970
color5       #928C7A
color13      #928C7A
color6       #717B83
color14      #717B83
color7       #b4b9bc
color15      #b4b9bc
